INSERT INTO exercise(name, english_name, category, equipment, difficulty, primary_muscle, secondary_muscles, description, instructions) VALUES
('杠铃卧推','Barbell Bench Press','STRENGTH','BARBELL','INTERMEDIATE','CHEST','TRICEPS,FRONT_DELTS','经典水平推举动作','肩胛后缩，双脚踩稳，控制下放后推起'),
('深蹲','Back Squat','STRENGTH','BARBELL','INTERMEDIATE','QUADRICEPS','GLUTES,HAMSTRINGS,CORE','经典下肢复合动作','保持躯干稳定，膝盖与脚尖方向一致'),
('硬拉','Deadlift','STRENGTH','BARBELL','INTERMEDIATE','HAMSTRINGS','GLUTES,BACK,CORE','髋主导全身力量动作','背部中立，贴腿拉起杠铃'),
('站姿推举','Overhead Press','STRENGTH','BARBELL','INTERMEDIATE','SHOULDERS','TRICEPS,CORE','垂直推举动作','收紧核心，杠铃沿面部前方垂直移动'),
('引体向上','Pull Up','STRENGTH','BODYWEIGHT','INTERMEDIATE','BACK','BICEPS,REAR_DELTS','自重垂直拉动作','从完全悬垂开始，胸部向横杆靠近'),
('高位下拉','Lat Pulldown','STRENGTH','CABLE','BEGINNER','BACK','BICEPS','背阔肌垂直拉动作','肩膀下沉，将横杆拉向上胸'),
('杠铃划船','Barbell Row','STRENGTH','BARBELL','INTERMEDIATE','BACK','BICEPS,REAR_DELTS','自由重量水平拉动作','髋部后移，保持背部中立向腹部拉'),
('坐姿划船','Seated Cable Row','STRENGTH','CABLE','BEGINNER','BACK','BICEPS,REAR_DELTS','器械水平拉动作','保持躯干稳定，肘部向后拉'),
('上斜哑铃卧推','Incline Dumbbell Press','STRENGTH','DUMBBELL','INTERMEDIATE','CHEST','TRICEPS,FRONT_DELTS','上胸推举动作','长凳调至约三十度，控制全程'),
('哑铃侧平举','Dumbbell Lateral Raise','STRENGTH','DUMBBELL','BEGINNER','SHOULDERS','','三角肌中束孤立动作','轻微屈肘，抬至肩高'),
('哑铃弯举','Dumbbell Curl','STRENGTH','DUMBBELL','BEGINNER','BICEPS','FOREARMS','肱二头肌孤立动作','固定上臂，完整屈伸肘关节'),
('绳索下压','Triceps Pushdown','STRENGTH','CABLE','BEGINNER','TRICEPS','','肱三头肌孤立动作','固定肘部，完全伸展'),
('前蹲','Front Squat','STRENGTH','BARBELL','ADVANCED','QUADRICEPS','GLUTES,CORE','前置杠铃深蹲','肘部抬高，躯干保持直立'),
('罗马尼亚硬拉','Romanian Deadlift','STRENGTH','BARBELL','INTERMEDIATE','HAMSTRINGS','GLUTES,BACK','髋铰链训练动作','保持小腿近乎垂直，髋部后移'),
('腿举','Leg Press','STRENGTH','MACHINE','BEGINNER','QUADRICEPS','GLUTES,HAMSTRINGS','器械下肢推举','腰背贴紧靠垫，膝盖跟随脚尖'),
('保加利亚分腿蹲','Bulgarian Split Squat','STRENGTH','DUMBBELL','INTERMEDIATE','QUADRICEPS','GLUTES,HAMSTRINGS','单侧下肢动作','后脚抬高，前脚稳定下蹲'),
('腿屈伸','Leg Extension','STRENGTH','MACHINE','BEGINNER','QUADRICEPS','','股四头肌孤立动作','控制伸膝和离心回落'),
('腿弯举','Leg Curl','STRENGTH','MACHINE','BEGINNER','HAMSTRINGS','','腘绳肌孤立动作','髋部贴紧，屈膝至充分收缩'),
('臀推','Hip Thrust','STRENGTH','BARBELL','INTERMEDIATE','GLUTES','HAMSTRINGS','臀肌髋伸动作','下巴微收，顶端充分伸髋'),
('站姿提踵','Standing Calf Raise','STRENGTH','MACHINE','BEGINNER','CALVES','','小腿训练动作','全幅度下降脚跟并踮起'),
('俯卧撑','Push Up','STRENGTH','BODYWEIGHT','BEGINNER','CHEST','TRICEPS,CORE','基础自重推举','身体保持直线，胸部接近地面'),
('双杠臂屈伸','Dips','STRENGTH','BODYWEIGHT','INTERMEDIATE','TRICEPS','CHEST,FRONT_DELTS','自重推举动作','肩胛稳定，下降至舒适深度'),
('窄距卧推','Close Grip Bench Press','STRENGTH','BARBELL','INTERMEDIATE','TRICEPS','CHEST','肱三头肌复合动作','握距略窄于肩，肘部贴近躯干'),
('飞鸟','Cable Fly','STRENGTH','CABLE','BEGINNER','CHEST','FRONT_DELTS','胸肌孤立动作','保持手肘角度，双臂向中线合拢'),
('反向飞鸟','Reverse Fly','STRENGTH','DUMBBELL','BEGINNER','REAR_DELTS','UPPER_BACK','肩后束训练','保持肩膀下沉，向两侧展开'),
('面拉','Face Pull','STRENGTH','CABLE','BEGINNER','REAR_DELTS','UPPER_BACK,ROTATOR_CUFF','肩部健康水平拉动作','绳索拉向面部，外旋上臂'),
('阿诺德推举','Arnold Press','STRENGTH','DUMBBELL','INTERMEDIATE','SHOULDERS','TRICEPS','多平面肩推动作','旋转同时推起，保持躯干稳定'),
('锤式弯举','Hammer Curl','STRENGTH','DUMBBELL','BEGINNER','BICEPS','FOREARMS','中立握弯举','掌心相对，固定上臂'),
('牧师凳弯举','Preacher Curl','STRENGTH','BARBELL','BEGINNER','BICEPS','','二头肌孤立动作','上臂贴垫，避免底部过伸'),
('仰卧臂屈伸','Skull Crusher','STRENGTH','BARBELL','INTERMEDIATE','TRICEPS','','三头肌孤立动作','固定上臂，杠铃向额头后方下降'),
('农夫走','Farmers Walk','STRENGTH','DUMBBELL','BEGINNER','FOREARMS','CORE,TRAPS','负重行走动作','保持高大姿势，步伐稳定'),
('平板支撑','Plank','STRENGTH','BODYWEIGHT','BEGINNER','CORE','GLUTES','抗伸展核心动作','收紧腹臀，身体保持直线'),
('悬垂举腿','Hanging Leg Raise','STRENGTH','BODYWEIGHT','INTERMEDIATE','CORE','HIP_FLEXORS','悬垂核心训练','避免摆动，骨盆后倾抬腿'),
('俄罗斯转体','Russian Twist','STRENGTH','BODYWEIGHT','BEGINNER','CORE','OBLIQUES','旋转核心动作','胸椎旋转，腰椎保持稳定'),
('壶铃摆动','Kettlebell Swing','CARDIO','DUMBBELL','INTERMEDIATE','GLUTES','HAMSTRINGS,CORE','爆发髋伸体能动作','髋铰链发力，不用手臂抬铃'),
('波比跳','Burpee','CARDIO','BODYWEIGHT','INTERMEDIATE','FULL_BODY','CORE','全身心肺动作','保持节奏和落地稳定'),
('开合跳','Jumping Jack','CARDIO','BODYWEIGHT','BEGINNER','FULL_BODY','','基础心肺热身','轻柔落地，手脚协调'),
('登山跑','Mountain Climber','CARDIO','BODYWEIGHT','BEGINNER','CORE','SHOULDERS,HIP_FLEXORS','动态核心心肺动作','保持躯干稳定，交替提膝'),
('跑步机跑步','Treadmill Run','CARDIO','MACHINE','BEGINNER','LEGS','CARDIOVASCULAR','室内有氧跑步','选择适合配速，保持自然步态'),
('划船机','Rowing Machine','CARDIO','MACHINE','INTERMEDIATE','FULL_BODY','BACK,LEGS','全身有氧动作','先蹬腿再后仰拉手，反向恢复'),
('椭圆机','Elliptical','CARDIO','MACHINE','BEGINNER','LEGS','CARDIOVASCULAR','低冲击有氧训练','保持躯干直立，均匀发力'),
('动感单车','Stationary Bike','CARDIO','MACHINE','BEGINNER','LEGS','CARDIOVASCULAR','低冲击骑行训练','调整座高，膝盖保持自然轨迹'),
('猫牛式','Cat Cow','MOBILITY','BODYWEIGHT','BEGINNER','SPINE','','脊柱活动练习','配合呼吸缓慢屈伸脊柱'),
('世界最佳拉伸','Worlds Greatest Stretch','MOBILITY','BODYWEIGHT','INTERMEDIATE','HIPS','THORACIC_SPINE','全身动态活动','弓步后旋转胸椎，两侧交替'),
('髋屈肌拉伸','Hip Flexor Stretch','MOBILITY','BODYWEIGHT','BEGINNER','HIP_FLEXORS','QUADRICEPS','髋前侧拉伸','骨盆后倾后轻微前移'),
('肩关节绕环','Shoulder Circles','MOBILITY','BODYWEIGHT','BEGINNER','SHOULDERS','','肩关节热身','在无痛范围缓慢画圈'),
('胸椎旋转','Thoracic Rotation','MOBILITY','BODYWEIGHT','BEGINNER','THORACIC_SPINE','SHOULDERS','胸椎活动练习','固定骨盆，旋转上背'),
('脚踝背屈','Ankle Dorsiflexion','MOBILITY','BODYWEIGHT','BEGINNER','ANKLES','CALVES','踝关节活动练习','脚跟不离地，膝盖向前移动'),
('鸽子式','Pigeon Pose','MOBILITY','BODYWEIGHT','INTERMEDIATE','GLUTES','HIPS','臀髋静态拉伸','保持髋部摆正，在舒适范围停留'),
('儿童式','Child Pose','MOBILITY','BODYWEIGHT','BEGINNER','BACK','SHOULDERS','放松和背部拉伸','臀部向脚跟坐，双臂向前延伸');
